# Generated by Django 3.1.2 on 2020-10-30 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='url',
            field=models.SlugField(default=0, max_length=130, unique=True),
        ),
    ]
