# Generated by Django 3.1.2 on 2020-10-31 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='teacher',
        ),
        migrations.AddField(
            model_name='task',
            name='clas',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='website.clas'),
            preserve_default=False,
        ),
    ]
