# Generated by Django 3.1.2 on 2020-10-31 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20201031_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='clas',
        ),
        migrations.AddField(
            model_name='task',
            name='clas',
            field=models.ManyToManyField(to='website.Clas'),
        ),
    ]
